name: eye_care
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  bloc: ^8.1.4
  build_runner: ^2.4.9
  cached_network_image: ^3.4.0
  cupertino_icons: ^1.0.6
  dio: ^5.5.0+1
  dropdown_search: ^5.0.6
  easy_localization: ^3.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_launcher_icons: ^0.13.1
  flutter_localization: ^0.2.1
  flutter_native_splash: ^2.4.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  get_it: ^7.7.0
  image_picker: ^1.1.2
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  logger: ^2.4.0
  lottie: ^3.1.2
  percent_indicator: ^4.2.3
  permission_handler: ^11.3.1
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.2
  shared_preferences: ^2.3.1
  smooth_page_indicator: ^1.2.0+3
  social_auth_buttons: ^2.0.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/Svgs/

flutter_intl:
  enabled: true
