name: eye_care
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  audioplayers: ^6.1.0
  bloc: ^8.1.4
  bottom_bar: ^2.0.3
  build_runner: ^2.4.9
  cached_network_image: ^3.4.0
  cupertino_icons: ^1.0.6
  device_preview: ^1.2.0
  dio: ^5.5.0+1
  dropdown_search: ^5.0.6
  easy_localization: ^3.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_launcher_icons: ^0.13.1
  flutter_localization: ^0.2.1
  flutter_native_splash: ^2.4.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  get_it: ^7.7.0
  google_maps_flutter: ^2.9.0
  image_picker: ^1.1.2
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  logger: ^2.4.0
  lottie: ^3.1.2
  percent_indicator: ^4.2.3
  permission_handler: ^11.3.1
  persistent_bottom_nav_bar: ^6.2.1
  pin_code_fields: ^8.0.1
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.2
  shared_preferences: ^2.3.1
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.0+3
  social_auth_buttons: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/Svgs/
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
flutter_intl:
  enabled: true
